# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: rouge
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"
gems: [jekyll-paginate]

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://www.sheldonyin.website


title : 望蜀得陇的空间

author:
  name: Sheldon Yin
  role: 安卓开发与前端开发爱好者
  email: 383541990@qq.com
  github: Sheldon-Yin
  twitter: None
  facebook: None
  googleplus: None
  bio: "Stay hungry, I am really hungry"
  Sheldon-Yin: http://www.sheldonyin.website/sheldon.jpg
